### ISSUE TITLE
Adição de função e sugestão

### ISSUE THREAD

**Issue by wesleyara** [vitoriadevalois/jogo-de-adivinhacao#1]
Muito interessante a ideia de criação de um jogo de adivinhação, com base nisso eu pensei se não seria possível a implementação desde mesmo conceito sobre o Math.random() para a criação de uma espécie de parâmetros sobre probabilidade, como por exemplo um lançamento de dados de 20 lados. Pensando nessa perspectiva que tenho sobre o RPG de mesa, seria viável a criação de vários "dados" utilizando essa mesma ideia do seu jogo de adivinhação.

E minha sugestão é quanto a escrita do código, que talvez seja de sua escolha fazer isso, mas tem a possibilidade de utilizar (`string ${var} string`) fazendo uso do ${} para inserir uma variável, invés de usar o método de concatenação, ("string" + var + "string").

**Comment by vitoriadevalois** [comment]
Muito interessante! Obrigada pela sugestão :)
